export interface IInsightCreate {
  type: string;
  project_id?: string;
  provider?: string;
  model?: string;
  prompt?: string;
  response?: string;
  context_meta?: Record<string, unknown>;
  cached?: boolean;
}

export interface IInsightUpdate {
  provider?: string;
  model?: string;
  prompt?: string;
  response?: string;
  context_meta?: Record<string, unknown>;
  cached?: boolean;
}

/**
 * Structured AI response model for consistent output format.
 * Makes the UI easy to render with cards and structured blocking information.
 */
export interface IAgentResponse {
  summary: string;
  insights: Array<{
    title: string;
    description: string;
    severity: 'low' | 'medium' | 'high';
    evidence: string[];
  }>;
  recommendations: Array<{
    action: string;
    priority: 'low' | 'medium' | 'high';
    owner?: string;
    due_date?: string;
  }>;
  confidence: number;
  generated_at: Date;
}

/**
 * Project context data assembled from analytics, risk, and project information.
 * This is what gets sent to the AI model for analysis.
 */
export interface IProjectContext {
  project: {
    id: string;
    name: string;
    description: string;
    status: string;
  };
  analytics: {
    metrics: Array<{
      metric_type: string;
      value: number;
      breakdown: Record<string, unknown>;
      period: string;
    }>;
    health_score?: number;
    velocity?: number;
  };
  risks: {
    risk_level: string;
    factors: string[];
    predictions: Array<{
      kind: string;
      risk_level: string;
      confidence_score: number;
      summary: string;
    }>;
  };
  blockers: string[];
  sprint_data: {
    current_sprint?: string;
    velocity?: number;
    completion_rate?: number;
  };
  plan?: {
    name: string;
    summary: string;
    items: Array<{
      title: string;
      kind: string;
      status: 'pending' | 'completed';
      description?: string;
    }>;
  };
}

/**
 * Chat session for maintaining conversation history.
 */
export interface IChatSession {
  session_id: string;
  project_id?: string;
  messages: Array<{
    role: 'user' | 'assistant';
    content: string;
    timestamp: Date;
  }>;
  created_at: Date;
  updated_at: Date;
}

/**
 * Provider configuration for multi-vendor support.
 */
export interface IProviderConfig {
  name: string;
  type: 'google' | 'openai' | 'anthropic' | 'ollama';
  api_key?: string;
  base_url?: string;
  model?: string;
  is_default: boolean;
  is_active: boolean;
}

/**
 * Department-wise team breakdown for plan generation.
 * If provided, the AI will distribute work across these departments.
 * If team_breakdown is provided, team_size is calculated automatically as the sum.
 */
export interface ITeamBreakdown {
  ui?: number;
  backend?: number;
  app?: number;
  others?: number;
}

/**
 * Input for the AI sprint-plan generator (POST /v1/plans).
 * Only `description` is required — every other field tunes the generated plan.
 * The AI will intelligently decide team_size, duration_weeks, and sprint_length_weeks
 * if they are not provided, using context from the description and any rules given.
 */
export interface IPlanGenerate {
  description: string;
  project_name?: string;
  project_id?: string;
  team_size?: number;
  team_breakdown?: ITeamBreakdown;
  duration_weeks?: number;
  sprint_length_weeks?: number;
  start_date?: string;
  deadline?: string;
  rules?: string;
  features?: string[];
  constraints?: string[];
  /**
   * When true, the service will compute team-size suggestions and embed them
   * in the generated plan's assumptions. Helpful when the user leaves team
   * fields empty and wants the AI to propose an optimal team configuration.
   */
  ask_team_suggestion?: boolean;
  /** Generated by the service when ask_team_suggestion is used. */
  team_suggestions?: ITeamSuggestion[];
  /**
   * Detailed task-level scope with assignee, estimated hours, and actual hours.
   * Used to inform the AI about the real workload and team capacity.
   */
  task_scope?: IPlanTaskScope[];
}

/** A single task with assignee, estimated hours, and actual/spent hours. */
export interface IPlanTaskScope {
  /** Human-readable task name or title. */
  task: string;
  /** Team member assigned to the task. */
  assignee: string;
  /** Estimated hours to complete the task. */
  estimate_hours: number;
  /** Actual hours spent or committed (can be larger than estimate). */
  actual_hours: number;
  /** Optional category/grouping for the task (e.g., "Payment", "Delivery"). */
  category?: string;
  /** Optional priority. */
  priority?: 'low' | 'medium' | 'high' | 'critical';
}

/** Suggestion block describing an ideal team composition for a project. */
export interface ITeamSuggestion {
  suggested_team_size: number;
  breakdown: ITeamBreakdown;
  rationale: string;
  role_hints: { role: string; count?: number }[];
}

export interface IPlanTask {
  title: string;
  description?: string;
  type?: string;
  priority?: string;
  assignee_role?: string;
  estimate_hours?: number;
  story_points?: number;
}

export interface IPlanSprint {
  index?: number;
  name: string;
  goal?: string;
  start_date?: string;
  end_date?: string;
  deadline?: string;
  planned_points?: number;
  tasks: IPlanTask[];
}

export interface IPlanMilestone {
  name: string;
  date?: string;
  description?: string;
}

export interface IPlanDeadline {
  label: string;
  date?: string;
}

export interface IPlanRisk {
  description: string;
  severity?: string;
  mitigation?: string;
}

/**
 * Structured plan JSON returned by the AI provider (or the heuristic
 * fallback). Sprint/deadline dates are always normalized server-side.
 */
export interface ISprintPlan {
  plan_name: string;
  summary: string;
  total_duration_weeks?: number;
  sprints: IPlanSprint[];
  milestones?: IPlanMilestone[];
  deadlines?: IPlanDeadline[];
  risks?: IPlanRisk[];
  assumptions?: string[];
  generated_by?: string;
  /**
   * Optional team breakdown. Included only when the client does not provide one.
   */
  team_breakdown?: ITeamBreakdown;
}

/**
 * Execution-tracking types for an accepted plan. Each accepted plan expands
 * into `plan_execution_items` rows — one per checkable item — stored apart
 * from the real `sprints` / `work_items` collections.
 */
export type PlanExecutionKind = 'sprint' | 'task' | 'milestone' | 'deadline' | 'dependency';

export interface IPlanExecutionItemCreate {
  plan_id: string;
  project_id?: string;
  kind: PlanExecutionKind;
  ref_key: string;
  parent_key?: string;
  title: string;
  description?: string;
  sequence?: number;
  meta?: Record<string, unknown>;
}

export interface IToggleExecutionItem {
  is_completed: boolean;
}

/**
 * Compact, stored project context. Assembled from project/analytics/risk data,
 * real sprints + work items, and accepted plan-execution progress, then
 * summarized by the AI provider (deterministic fallback) and hard-capped to
 * PROJECT_CONTEXT_MAX_LINES / PROJECT_CONTEXT_MAX_CHARS. Persisted on
 * `projects.project_context` and consumed by the AI chat.
 */
export const PROJECT_CONTEXT_MAX_LINES = 50;
export const PROJECT_CONTEXT_MAX_CHARS = 2500;

export type ProjectContextTrigger = 'plan_create' | 'plan_accept' | 'plan_item_update' | 'git_sync' | 'taiga_sync' | 'manual';

export interface IProjectContextSnapshot {
  text: string;
  generated_by: 'ai' | 'heuristic';
  sources: string[];
  line_count: number;
  char_count: number;
  trigger: ProjectContextTrigger;
  updated_at: Date;
}

export interface IProjectContextBundle extends IProjectContextSnapshot {
  git: IProjectContextSnapshot;
  taiga: IProjectContextSnapshot;
  plan: IProjectContextSnapshot;
  combined: IProjectContextSnapshot;
}
